### ISSUE TITLE
Some datasets from the UEA & UCR Time Series Classification Archive do not contain arff files.

### ISSUE THREAD

**Issue by thuanbuianh** [johannfaouzi/pyts#136]
#### Description
Hi, I tried to load the dataset Ering using pyts 0.12.0 and an issue raised: "FileNotFoundError: [Errno 2] No such file or directory: '/usr/local/lib/python3.7/dist-packages/pyts/datasets/cached_datasets/UEA/ERing/ERing_TRAIN.arff'". It looks like some datasets from the UEA & UCR Time Series Classification Archive do not contain arff files. 

#### Steps/Code to Reproduce

```python
<< 
from pyts.datasets import fetch_uea_dataset
X, y = fetch_uea_dataset('Ering', return_X_y=True) 
>>
```

#### Versions

NumPy 1.21.6
SciPy 1.7.3
Scikit-Learn 1.0.2
Numba 0.56.3
Pyts 0.12.0

**Comment by johannfaouzi** [comment]
Hi,

Indeed, it seems like the dataset is now available in the `sktime` format (`.ts`). The dataset used to be available in a different format (`.arff`), but it's no longer the case. It's hard for me to track these changes because I don't run the website that hosts the datasets.

The easiest solution, if you don't mind downloading the file and unzipping the file (i.e., not in Python), is this one:
```python
import os
from sktime.datasets import load_from_tsfile

path = ''  # Folder with the unzipped dataset
X_train, y_train = load_from_tsfile(os.path.join(path, 'ERing_TRAIN.ts'), return_data_type="numpy3d")
X_test, y_test = load_from_tsfile(os.path.join(path, 'ERing_TEST.ts'), return_data_type="numpy3d")
```

If you want to do everything in Python, you could download the file, unzip it and write the files to disk. If you need such a more automatic version (because there are many datasets like this one), I could give you such an example.

Hope this helps you a bit.

**Comment by thuanbuianh** [comment]
Thanks for your quick support!
