### ISSUE TITLE
Difference between SAX and KBinsDiscretizer

### ISSUE THREAD

**Issue by janthmueller** [johannfaouzi/pyts#142]
Is there any difference between the SAX with an 'ordinal' alphabet and the KBinsDiscretizer?

```
def transform(self, X):
        """Bin the data with the given alphabet.

        Parameters
        ----------
        X : array-like, shape = (n_samples, n_timestamps)
            Data to transform.

        y
            Ignored

        Returns
        -------
        X_new : array, shape = (n_samples, n_timestamps)
            Binned data.

        """
        X = check_array(X, dtype='float64')
        n_timestamps = X.shape[1]
        alphabet = self._check_params(n_timestamps)
        discretizer = **KBinsDiscretizer**(
            n_bins=self.n_bins, strategy=self.strategy)
        indices = discretizer.fit_transform(X)
        if isinstance(alphabet, str):
            return indices
        else:
            return alphabet[indices]
```

If not can I reproduce the original algorithm by building a pipeline usining:
 - Standard Scaler
 - PAA
 - KBinsDiscretizer using normal strategy

or should I use the Standard Scaler after PAA?

**Comment by johannfaouzi** [comment]
`KBinsDiscretizer` is different from SAX because SAX is a "row-wise" discretization (i.e., discretizing each time series independently) while `KBinsDiscretizer` is a "column-wise" discretization (i.e., discretizing each column independently). `KBinsDiscretizer` is used for the Symbolic Fourier Approximation (SFA) algorithm which discretizes the Fourier coefficients of a time series.

If you want to reproduce the original SAX algorithm, you indeed need a pipeline consisting of:
* StandardScaler (so that each time series has zero mean and unit variance)
* PAA (to decrease the number of time points in the time series)
* SAX with normal strategy (to use the the quantiles of the standard normal distribution as cut-off values)

**Comment by johannfaouzi** [comment]
Sorry for my mistake, what I said is indeed totally wrong.

When you mentioned KBinsDiscretizer, I actually thought about MultipleCoefficientBinning, which performs the discretization column-wise and is used in Symbolic Fourier Approximation.

KBinsDiscretizer is very similar to SAX indeed, it's just that it does not support the alphabet argument. If you look at the source code of SAX, you can see that it just uses KBinsDiscretizer and takes care of returning symbols (instead of integers) if necessary. KBinsDiscretizer is mainly there to provide most of the preprocessing tools in scikit-learn (which are applied column-wise, feature-wise) to pyts (which are applied row-wise, sample-wise).

https://github.com/johannfaouzi/pyts/blob/24345921f09c608f75be99c7f1fcb4ea19c63676/pyts/approximation/sax.py#L94-L102
