### ISSUE TITLE
MTF np.digitize error: bins must be monotonically increasing or decreasing

### ISSUE THREAD

**Issue by ThatEpicDude** [johannfaouzi/pyts#20]
Hi,

I am creating MTF matrices from the [Lightning2](http://www.timeseriesclassification.com/description.php?Dataset=Lightning2) time-series dataset using the pyts module. When entering a high number for the quantile bins (n_bins) the MTF transformation does not succeed:

```
from scipy.io import arff
import pandas as pd
from pyts.image import GASF, GADF, MTF

lighttrain = arff.loadarff('Datasets/Lightning2/Lightning2_TRAIN.arff')
dftrain0 = pd.DataFrame(lighttrain[0])
dftrain = dftrain0.drop('target', axis=1) #taking away the class labels

matsize = 16
qsize = 40

dfmtftr = MTF(matsize,n_bins=qsize).fit_transform(dftrain)
```

Error in console:

> File "/anaconda3/lib/python3.6/site-packages/sklearn/base.py", line 462, in fit_transform
>     return self.fit(X, **fit_params).transform(X)
>   File "/anaconda3/lib/python3.6/site-packages/pyts/image/image.py", line 310, in transform
>     for i in range(n_samples)])
>   File "/anaconda3/lib/python3.6/site-packages/pyts/image/image.py", line 310, in <listcomp>
>     for i in range(n_samples)])
> ValueError: bins must be monotonically increasing or decreasing

theoretically I should be able to sort the data into as many bins as I want, shouldn't I? I cannot see a reason in the `image.py` source-code why the error should occur at `n_bins=40` but not at `n_bins=8`. Are there specific boundaries for `image_size` and `n_bins`?
The source time-series has a length of 637.

**Comment by johannfaouzi** [comment]
Hi,

As the traceback shows, the error comes from the following lines:
https://github.com/johannfaouzi/pyts/blob/b4167ad6850ccd8dae6aa8ba3d2b0f6fbcbc82af/pyts/image/image.py#L309-L310

The error message is raised by the [numpy.digitize](https://docs.scipy.org/doc/numpy-1.15.1/reference/generated/numpy.digitize.html) function: the parameter `bins` must be *1-dimensional and monotonic*. Here, the issue is that the bins are not monotonic. More precisely, at least two back-to-back elements are equal. This can happen when the distribution of a time series is "weird".

I'm going to give you a simple example: let's take a time series with 100 timestamps whose first 50 values are equal to 0 and the last 50 values are equal to ``np.arange(50)``. Let's compute 4 bins with ``quantiles='empirical'`` (i.e. the bin edges correspond to the 0.25, 0.5, 0.6 and 0.75 quantiles):
```python
time_series = np.r_[np.zeros(50), np.arange(50)]
n_bins = 4

bin_edges = np.percentile(time_series, np.linspace(0, 100, n_bins + 1)[1:-1])
```
If you print ``bin_edges``, you will see that it is equal to ``array([ 0.  ,  0.  , 24.25])``, i.e. the first quartile is equal to 0, the second quartile to 0 and the third quartile to 24.25.

Now there are two issues: a theoretical issue and a computational issue.

The theoretical issue is the following one: in which bin would you put all the elements of ``time_series`` that are equal to 0. In the first bin or in the second bin? You could delete some bin edges in that scenario, but you would end up with a different number of bins for each time series, and it might be an issue.

The computational issue is about float precision. Sometimes, when the bin edges are computed, two bin edges that should be equal in theory are not equal in practice. In that case, [numpy.digitize](https://docs.scipy.org/doc/numpy-1.15.1/reference/generated/numpy.digitize.html) raises the error that you experienced: ``bins must be monotonically increasing or decreasing``.

In your example, a time series with length 637 and 40 bins means that each bin will have 15 to 16 values. If one time series has 16 or more timestamps with the same values, you end up with two back-to-back quantiles that are equal.

I just checked and in that dataset, there are a lot of timestamps where the time series are equal to the minimum values. This means that you have back-to-back quantiles that are equal *in theory*, but slightly different *in practice* (like ``1e-17``), and if that difference is negative, the error message occurs. Here is some piece of code to illustrate this:
```python
n_bins = 20
bin_edges = np.percentile(dftrain.values, np.linspace(0, 100, n_bins + 1)[1:-1], axis=1)

print(bin_edges[:, 9])

[-0.41955627 -0.41955627 -0.41955627 -0.30234242 -0.17496895 -0.15985198
 -0.14848576 -0.13745187 -0.12880852 -0.11856567 -0.1049761  -0.09267081
 -0.07719069 -0.05667091 -0.03954731 -0.00508399  0.04006007  0.13114008
  0.39045929]

print(np.diff(bin_edges[:, 9]))

[ 5.55111512e-17 -5.55111512e-17  1.17213848e-01  1.27373472e-01
  1.51169700e-02  1.13662220e-02  1.10338880e-02  8.64334800e-03
  1.02428520e-02  1.35895680e-02  1.23052944e-02  1.54801126e-02
  2.05197844e-02  1.71235986e-02  3.44633259e-02  4.51440543e-02
  9.10800138e-02  2.59319212e-01]
```
You can see that the second element is negative, which is a computational issue.

I will try to update the code to account for that scenario. Don't hesitate to ask more questions if my explanations are not clear enough.

Best,
Johann

**Comment by ThatEpicDude** [comment]
Thanks for your quick and detailed reply Johann.

Unfortunately this reply has raised some new questions I didn't know I had before. As I am quite new to programming I don't have a lot of experience with the numpy functions.
I had a look at your first example:
```
time_series = np.r_[np.zeros(50), np.arange(50)]
n_bins = 4

bin_edges = np.percentile(time_series, np.linspace(0, 100, n_bins + 1)[1:-1])

print(np.linspace(0, 100, n_bins + 1)[1:-1])
print(bin_edges)
```
Out:
```
[25. 50. 75.]
[ 0.    0.   24.25]
```
It behaved just like you said. From what I understand `np.percentile(a, q)` returns `min(a) + (max(a)-min(a)) * q/100` which in this case should return `[12.5, 25, 37.5]` and not `[0, 0, 24.25]`. These would also be the intuitive bin borders I would think of considering the MTF description in the [original paper by Wang, Oates](https://arxiv.org/abs/1506.00327). Obviously I am understanding something wrong, but what?

**Comment by johannfaouzi** [comment]
That's not my understanding. There are several ways to compute bins. Using the definition in [KBinsDiscretizer](https://scikit-learn.org/stable/modules/generated/sklearn.preprocessing.KBinsDiscretizer.html) from scikit-learn, the way you compute bins would be `'uniform'` (i.e. each bin has the same length), whereas `'quantile`' gives bins with the same number of points in each bin. See [Wikipedia's page about quantile](https://en.wikipedia.org/wiki/Quantile).

You can also have a look at [this paper](https://www2.informatik.hu-berlin.de/~schaefpa/sfa_trie.pdf) where it is called `Multiple Coefficient Binning`(page 4), with the distinction between `equi-width`and `equi-depth`(however Multiple Coefficient Binning bins the data column-wise).

The next release will adopt the scikit-learn convention. The parameter `quantiles` will be replaced by `strategy` with three possible values: `uniform`, `quantile` and `normal`. 

Best,
Johann

**Comment by ThatEpicDude** [comment]
Thank you again for your quick reply.

I understand now. The restriction on `n_bins` results from the particular time-series I was using. In the Wang, Oates paper they speak of "quantile bins", so I assume your code is actually more correct than my previous understanding.

Similarly when trying different values for `image_size` on this data set. It often produces an "out of bounds"-error. Using my previous code but with a larger `image_size`:
```
matsize = 48
qsize = 10
dfmtftr = MTF(matsize,n_bins=qsize).fit_transform(dftrain)
```
produces the Traceback and error:

> File "/anaconda3/lib/python3.6/site-packages/sklearn/base.py", line 462, in fit_transform
>     return self.fit(X, **fit_params).transform(X)
>   File "/anaconda3/lib/python3.6/site-packages/pyts/image/image.py", line 317, in transform
>     remainder)
>   File "/anaconda3/lib/python3.6/site-packages/numpy/lib/shape_base.py", line 357, in apply_along_axis
>     res = asanyarray(func1d(inarr_view[ind0], *args, **kwargs))
>   File "/anaconda3/lib/python3.6/site-packages/pyts/image/image.py", line 351, in _mtf
>     AMTF[i, j] = MTF[start[i]:end[i], start[j]:end[j]].mean()
> IndexError: index 46 is out of bounds for axis 0 with size 46

do you have any more information on the restrictions of `image_size`?

**Comment by johannfaouzi** [comment]
It's not a restriction, but a bug (thanks for finding it out).

It comes from this line:
https://github.com/johannfaouzi/pyts/blob/b4167ad6850ccd8dae6aa8ba3d2b0f6fbcbc82af/pyts/image/image.py#L347

This function is defined in the `utils` module:
https://github.com/johannfaouzi/pyts/blob/b4167ad6850ccd8dae6aa8ba3d2b0f6fbcbc82af/pyts/utils/utils.py#L15-L67

As mentioned in the article, the size of the image is reduced by applying a blurring kernel. In practice, it means that you take a batch of pixels (a square or a rectangle) and you take the mean in that batch.

The bug comes from the lack of definition for the parameter `n_segments` when the `segmentation` function is called. Here is what is happening:

* The size of the image is currently 637. We want to decrease this number to 48.
* First, the size of the patch is computed. This size is equal to ``(637 // 48) + 1 = 14`` (because 48 does not divide 637, thus the +1).
* Then the `segmentation` function computes the indices for each batch. However, the number of batches is not given with the current code (which is a bug). Thus, this number is recomputed with the following formula ``(637 // 14) + 1 = 46`` (because 14 does not divide 637, thus the +1).
* Because the number of batches is smaller than expected (46 < 48), you get the error `IndexError: index 46 is out of bounds for axis 0 with size 46`: the arrays `start` and `end` have a size equal to 46 but the code tries to get the 47th element (index 46 since we start at 0).
* Another issue: This creates sometimes empty batches, and when you take the mean of an empty batch (whose length is equal to 0), you get an error (or sometimes a warning) because there is a division by zero.

Thank you for finding this bug and sorry for the inconvenience.

Best,
Johann

**Comment by ThatEpicDude** [comment]
No problem. Thank you for writing this very useful module! (I had my own code for the Gramian Matrices and the MTF but yours is way more thought through and generally applicable)

I am also new to Github. If I wanted to use the `image_size` and `n_bins` like discussed above in say 2 days from now. How would I do it? Do you have time to update it? Should I try updating the `image.py` on my own computer and fix my issues?

**Comment by johannfaouzi** [comment]
There are two possibilities:
* First possibility (which relies on me): I update the `master` branch and upload a new version on PyPI. In this case, the only thing you have to do is to run `pip install --upgrade pyts`.
* Second possibility (which doesn't rely on me): you can either fork or clone the repository, install the package in editable mode (`pip install -e .` in the root directory), and then you can edit the code and the changes that you make will be directly live.

The upside of the second possibility is that you can make any change, whenever you want, if you feel like there are restrictions you don't want, or for whatever reasons. But you have to do it by yourself. The upside of the first possibility is that everyone can get the exact same code as long as they install the same version of the package from PyPI. Moreover, it's also my responsibility to maintain this package.

Since both bugs are definitely not intended, I'm going to update the code and push another version on PyPI. I'll post another comment when it's done.

Note: I've also been working offline for the past few months on a new version of the package that will bring major changes to the package with no backward compatibility (there will be many upsides with this version: much more optimized code, better test coverage, more algorithms available, etc.).

**Comment by johannfaouzi** [comment]
It should be good now, you can install version `0.7.5` from PyPI:
`pip install --upgrade pyts` or `pip install pyts==0.7.5`.

Please let me know if it works fine.

Best,
Johann

**Comment by ThatEpicDude** [comment]
Thank you, I installed the update. Quick runs seem to not give an error and the matrix shape is returned as desired.
