### ISSUE TITLE
Unit tests

### ISSUE THREAD

**Issue by rth** [johannfaouzi/pyts#3]
Very nice package. I was just wondering if there were any plans to add unit tests ?

**Comment by johannfaouzi** [comment]
To be honest, this package was a side project: I wanted to learn more about Python packages and I was working on a binary classification problem. Unit tests are a key thing that I didn't have time to do. I'm glad that you're mentioning them because they are very important and overlooking them was a bad idea. I'm going to work on that soon (I hope it's done by the end of the week).

I don't have much time to work on this package anymore and it's unlikely that other transformation or classification tools are added in the future. Any feedback to improve the current package are nonetheless very welcome and making this package as clean as possible is probably my last objective for this package.

**Comment by rth** [comment]
I understand, well I think that a last effort to package / tests the existing methods would be quite useful for potential users.

**Comment by johannfaouzi** [comment]
Thank you, I didn't know about that !

Should I update the setup.py file too (with pytest instead of nose) ?

**Comment by rth** [comment]
> Should I update the setup.py file too (with pytest instead of nose) ?

You could put `tests_require = ["pytest"]`. I would juste remove the "test_suite" fields, it's easier to run,

```
pytest pyts
```
than
```
python setup.py test
```

**Comment by johannfaouzi** [comment]
Alright, thank you once again !
