### ISSUE TITLE
MTF some arrays with no constant error!

### ISSUE THREAD

**Issue by cssaheel** [johannfaouzi/pyts#56]
The MTF example ( https://pyts.readthedocs.io/en/latest/auto_examples/image/plot_mtf.html ) ran on my machine, so I know the setup is complete. But for some reason I am getting this error when I pass my 2-D array:

> user@ubuntu:~/Desktop/pyts_ex$ python prog.py 
> Traceback (most recent call last):
>   File "prog.py", line 61, in <module>
>     x_train_np_new = mtf.fit_transform(x_train_np)
>   File "/home/user/.local/lib/python2.7/site-packages/sklearn/base.py", line 464, in fit_transform
>     return self.fit(X, **fit_params).transform(X)
>   File "/usr/local/lib/python2.7/dist-packages/pyts/image/mtf.py", line 142, in transform
>     X_binned = discretizer.fit_transform(X)
>   File "/home/user/.local/lib/python2.7/site-packages/sklearn/base.py", line 464, in fit_transform
>     return self.fit(X, **fit_params).transform(X)
>   File "/usr/local/lib/python2.7/dist-packages/pyts/preprocessing/discretizer.py", line 119, in transform
>     self._check_constant(X)
>   File "/usr/local/lib/python2.7/dist-packages/pyts/preprocessing/discretizer.py", line 140, in _check_constant
>     raise ValueError("At least one sample is constant.")
> ValueError: At least one sample is constant.
> 

My interpretation for this error is that pyts requires some kind of constant, which seems to be missing from my provided array, any thought how to fix this? Thanks.

**Comment by johannfaouzi** [comment]
Hi,

The error comes from this private method:
https://github.com/johannfaouzi/pyts/blob/10b7a7a1d19debcd13b239138b91adba8ad2d4c9/pyts/preprocessing/discretizer.py#L138-L140

If this error is raised, it means that there is at least one sample (i.e. one time series) that is constant. The [MarkovTransitionField](https://pyts.readthedocs.io/en/latest/generated/pyts.image.MarkovTransitionField.html#pyts.image.MarkovTransitionField) algorithm discretizes time series into `n_bins` bins, which would lead to a single bin if a time series is constant. It may be better to raise a warning rather than an error.

If you remove the constant time series from your 2D-array, this error will no longer be raised. You could find the corresponding indices using `np.where(np.var(x_train_np, axis=1) == 0)[0]`.

I hope that this helps a bit.

**Comment by wwjd1234** [comment]
I have this issue as well when padding my time series with zeros so that they are all the same length
